### ISSUE TITLE
heap-buffer-overflow in action_web_request

### ISSUE THREAD

**Issue by ballle98** [sfeakes/AqualinkD#88]
see ballle98/AqualinkD#37: main process exited, code=exited, status=1/FAILURE

```
08:13:21.215 Info:   URI request: '/api '
=================================================================
==14210==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xb4403680 at pc 0x0003e84c bp 0xbe969674 sp 0xbe969240
READ of size 1025 at 0xb4403680 thread T0
    #0 0x3e84b in StrstrCheck(void*, char*, char const*, char const*) (/home/pi/remote-debugging/aqualinkd+0x3e84b)
    #1 0x3eab3 in strstr (/home/pi/remote-debugging/aqualinkd+0x3eab3)
    #2 0x113787 in action_web_request C:\git\AqualinkD/net_services.c:629
    #3 0x118abf in ev_handler C:\git\AqualinkD/net_services.c:1073
    #4 0x13adbb in mg_call C:\git\AqualinkD/mongoose.c:2258
    #5 0x15d5f7 in mg_http_call_endpoint_handler C:\git\AqualinkD/mongoose.c:8463
    #6 0x152557 in mg_http_handler C:\git\AqualinkD/mongoose.c:6374
    #7 0x13adbb in mg_call C:\git\AqualinkD/mongoose.c:2258
    #8 0x13f88b in mg_recv_common C:\git\AqualinkD/mongoose.c:2706
    #9 0x13f8db in mg_if_recv_tcp_cb C:\git\AqualinkD/mongoose.c:2710
    #10 0x14565f in mg_handle_tcp_read C:\git\AqualinkD/mongoose.c:3608
    #11 0x146277 in mg_mgr_handle_conn C:\git\AqualinkD/mongoose.c:3733
    #12 0x148007 in mg_socket_if_poll C:\git\AqualinkD/mongoose.c:3925
    #13 0x13cfeb in mg_mgr_poll C:\git\AqualinkD/mongoose.c:2424
    #14 0xf9def in main_loop C:\git\AqualinkD/aqualinkd.c:1236
    #15 0xf811b in main C:\git\AqualinkD/aqualinkd.c:808
    #16 0xb6d03677 in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x16677)

0xb4403680 is located 0 bytes to the right of 1024-byte region [0xb4403280,0xb4403680)
allocated by thread T0 here:
    #0 0xbe557 in malloc (/home/pi/remote-debugging/aqualinkd+0xbe557)
    #1 0x145503 in mg_handle_tcp_read C:\git\AqualinkD/mongoose.c:3572
    #2 0x146277 in mg_mgr_handle_conn C:\git\AqualinkD/mongoose.c:3733
    #3 0x148007 in mg_socket_if_poll C:\git\AqualinkD/mongoose.c:3925
    #4 0x13cfeb in mg_mgr_poll C:\git\AqualinkD/mongoose.c:2424
    #5 0xf9def in main_loop C:\git\AqualinkD/aqualinkd.c:1236
    #6 0xf811b in main C:\git\AqualinkD/aqualinkd.c:808
    #7 0xb6d03677 in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x16677)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/pi/remote-debugging/aqualinkd+0x3e84b) in StrstrCheck(void*, char*, char const*, char const*)
Shadow bytes around the buggy address:
  0x36880680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x36880690: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x368806a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x368806b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x368806c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x368806d0:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368806e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa


```

**Comment by ballle98** [comment]
updated pull request to version 2.2.2a
